apiVersion: v1
kind: Service
metadata:
  name: analytics-api
  labels:
    app: analytics
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: analytics-api
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  labels:
    name: analytics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: analytics-api
  template:
    metadata:
      labels:
        service: analytics-api
    spec:
      containers:
      - name: analytics-api
        image: 954522806846.dkr.ecr.us-east-1.amazonaws.com/coworking-checkin:3
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
            - configMapRef:
                name: app-config
      restartPolicy: Always